1 In which month in 2023 did we originate the most loans?

(Hint) The table int_p_loans.int_p__loanapplication_credit_analytics__loans contains a column called is_originated which is 1 if the loan was originated and 0 if not

  origination_cohort  volume
0            2023-11   20917

2 How much did Lendable make in loan fees in 2024?

(Hint) Net amount is the loan amount the customer receives, gross amount is the net amount plus fees

   total_fees
0  61423546.0

3 How many days in December 2024 that had more than 1,000 originations were in the second half of the month (>= 16th)?

(Hint) A having statement can help filter on an aggregation

   number_of_days
0               2

4 What was the risk grade distribution of loans in June 2025? For an extra challenge, try to get the proportions too!

(Hint) For proportions try using a CTE (with statement) to collect and then aggregate data. If not can aggregate in excel/python

  risk_grade  volume proportion_of_loans
0          A    3922            0.096470
1          B    8201            0.201722
2          C    5897            0.145050
3          D    5811            0.142934
4          E    1985            0.048825
5          F    1795            0.044152
6         F*    2811            0.069143
7        F**   10233            0.251703

5 For each risk grade in June 2025, what was the min/max apr for originated loans?
(Hint) There's an apr field in int_p_loans.int_p__loanapplication_credit_analytics__loans

  risk_grade  min_apr  max_apr
0          A     8.09    24.30
1          B     8.21    31.86
2          C     9.42    43.39
3          D    10.50    48.87
4          E    18.92    48.88
5          F    32.87    48.89
6         F*    46.53    48.89
7        F**    46.55    48.89

7 Of all applications in July 2025, what proportion had an affordability assessment?

(Hint) If you had an affordability assessment, you're in the table mrt__affordability_decisions__loans which is NOT unique on application!

  proportion
0   0.353249

8 For each month, what was the cumulative count of loans originated in 2024?

(Hint) Try using an aggregation with a window function

   origination_cohort  volume cumulative_volume
0             2024-01   22622             22622
1             2024-02   19899             42521
2             2024-03   20771             63292
3             2024-04   24541             87833
4             2024-05   25722            113555
5             2024-06   25355            138910
6             2024-07   29262            168172
7             2024-08   29762            197934
8             2024-09   28400            226334
9             2024-10   27831            254165
10            2024-11   29635            283800
11            2024-12   27029            310829

9 In March 2025, how many loans were written in the bands  0 <= x < 10k, 10k <= x < 20k, x >= 20k?

(Hint) Try a case statement with netamount to segment loans

In [ ]:
(Resut is slightly different to the one shown below, but very similar.)

  loan_band  volume
0     0-10k   30716
1    10-20k    2019
2      20k+     459